### ISSUE TITLE
Already-transparent background in a program turns black upon enabling click-through feature

### ISSUE THREAD

**Issue by trilxs** [BiGilSoft/WindowTop#120]
It seems when I enable click-through on this window that already has transparency, it turns the transparency to black. 
Before enabling click-through: 
![image](https://user-images.githubusercontent.com/15008503/125138306-46713180-e0c3-11eb-8f8b-f59e5b470e28.png)
After enabling click-through:
![image](https://user-images.githubusercontent.com/15008503/125138399-6b65a480-e0c3-11eb-8766-d04aa102f620.png)
Unfortunately turning the background black hinders a few features of this program. It seems the opacity feature that auto-enables during the click-through is what's causing this. Perhaps separating the two features (click-through and opacity) might avoid this issue? I'm not sure, but any help would be wonderful. Thank you for your time!

**Comment by gileli121** [comment]
@trilxs 
I need to find where I can download this program of this window.
I searched for "OnScreenProtector" but I did not found download.

**Comment by trilxs** [comment]
@gileli121 Oh I'm so sorry, here's the link to that! https://sourceforge.net/projects/osprotractor/files/latest/download

**Comment by gileli121** [comment]
@trilxs 
Please try this build:
[Build 10.7.21-1.zip](https://github.com/BiGilSoft/WindowTop/files/6795039/Build.10.7.21-1.zip)

Let me know if it is fixed.
Note that if you will change the opacity, you will get the issue again.
But if you only using the click-through option without changing the opacity it should work fine.

The way I fixed it is that if the window EX_STYLE has the flag `WS_EX_LAYERED` from the beginning, than the click-through option will not modify the opacity because we assume that the window of the program already handling opacity in some way by its own.

**Comment by trilxs** [comment]
@gileli121 It works like a charm! Thank you so much for the swift fix and response! Heavily appreciated. Please keep up the great work.

**Comment by gileli121** [comment]
Great!
I will release the next version with fix for this issue
