### ISSUE TITLE
Convert license from MSI to Microsoft Store version

### ISSUE THREAD

**Issue by jongalloway** [BiGilSoft/WindowTop#126]
I have a license for the MSI version. I would like to switch over to the Microsoft Store version to get automatic updates. It looks like there isn't an option to enter an existing license key, only to purchase a new license. I understand this may not be easy or possible since they are different licensing systems.

**Comment by gileli121** [comment]
Thanks for your feedback.
We will see if there is an option to build a system on the official website that allows you to enter the key for the MSI version and then the system will block the old key and will give you redeem code for the MS Store version.

For now this process can be done maually by contacting support

**Comment by gileli121** [comment]
Thanks for your feedback.
I considered it. 
There is an issue with your request.
The price for the MS Store version is a little higher because I had to do it.
Microsoft taking a fee for every sale that I made.

If you purchase directly (and it is the key for the MSI version), you can pay less because of the fee saved.
If I will allow customers to convert MSI/Desktop key to redeem code it will make a problem. In such a case, a customer can purchase the regular key at a lower price and then ask to convert it to redeem code for the MS Store version.

So I prefer to not allow converting activation keys.
Anyway, the MSI/Desktop version will continue to get updates and I will not drop it.

**Comment by gileli121** [comment]
However, there is an option to sell directly reedem codes that will activate the MS Store version.
I have option to generate valid redeem codes without any cost that taken by Microsoft.. 
Then sell these redeem keys directly on the official website.

But I am not sure that it is right.. it is a way to sell product in MS Store while skipping Microsoft fee for each sale.
I like it..

But then the website will have 3 options to purchase the software:

1. Purchase the Microsoft Store version directly on the official website by purchasing redeem code that you enter in Microsoft Store. The price will be lower because I skip MS fee.
2. Purchase the Microsoft Store version via Microsoft Store purchase system. The price will be a little higher due to MS fee
3. Purchase regular activation key for the MSI/Desktop version. The price will be the same as the desktop version.

I think that it will look a little strange but it may be an option that I seey myself seriously considering it

**Comment by gileli121** [comment]
I added the option to purchase redeem code directly from the official website.
The cost is the same.

**Comment by gileli121** [comment]
Option removed and no longer valid.
It confused customers... They tried to use it in the installer/portable versions.

There is no way anymore to convert the activation key to MS Store.

However, I will see if I can find tricks for the MS Store API so that when you enter an activation key, it will register the activation key in the MS Store API per your account.. so in that way, you can somehow enter the activation key and it will activate it for your MS account.

For MS, it will not be considered as a real purchase, however, if I can somehow use the API to add meta-data that is specific for the account, the program can use this data and from it, it can know if it was activated.

I will investigate if it can be done

**Comment by gileli121** [comment]
For now, I decided that I will keep it as it is.
I already did change now that the store version is free like the installer/portable version.
You pay only for the full functionality.
