### ISSUE TITLE
Windows 11 Explorer Lag when moving windows.

### ISSUE THREAD

**Issue by ACastanza** [BiGilSoft/WindowTop#131]
Hello,

I noticed this issue on the last two builds of Windows 11, I know, prerelease, but I thought I'd let you know anyway.
After some indeterminate amount of time it appears that WindowTop causes Windows explorer windows and the mouse cursor to lag severely when attempting to move a window. The window and the cursor will move extremely slowly and sometimes windows will even generate a second cursor that responds normally while this is happening.

Restarting explorer.exe (from the task manager) alone did not help, I had to first kill WindowTop and then restart explorer.exe.

It only seems to happen after a day+ of uptime. Unfortunately I wasn't able to confirm if this happens or not on Windows 10, but it has occurred multiple times on 11.

Let me know if there's any logging I can do to help get the cause identified.

**Comment by ACastanza** [comment]
Changing the polling rate, the fix suggested in the reddit thread did not resolve the issue. I tried adjusting the polling rate (no fix), restarting explorer (no fix), setting the polling rate back, restarting explorer again (no fix), killing WindowTop and restarting explorer again (fix).

**Comment by gileli121** [comment]
There is also an option that the users from Reddit that reported it are using WindowTop :) 
But from how it looks on the recording, it does not looks like it.

I think first to wait for the issue to be fixed by Microsoft.
I know that you may be right that the issue was caused by WindowTop.
But I still prefer to wait that the issue that was reported on Reddit will be fixed.

I also don't like to develop/test the product on unstable Windows 11 releases.

For now, I can suggest some workaround that maybe will help.

1. Go to:
![image](https://user-images.githubusercontent.com/17680514/131386490-90dcfc63-0e2a-4c96-aa40-6f1fd1e09232.png)
2. Click on the+ button
![image](https://user-images.githubusercontent.com/17680514/131386610-9d715621-e6fd-4814-83db-501354086b55.png)
3. Select `explorer.exe` and click on `Add`
![image](https://user-images.githubusercontent.com/17680514/131386757-beedf49b-51ef-4011-8478-6390378e018c.png)

Let me know if after you did this workaround it fixed it for you.
I assume that it can help because this way you tell WindowTop to be disabled for some windows.
Maybe if it will be disabled for file explorer windows, the issue will be fixed for you.

However, this is not a real fix because if you want to set such windows on top, you will not be able to do it because you disabled the program.

However, if I will know that disabling WindowTop for some processes such as `explorer.exe` - is something that helps, I can know better the bug source and how to fix it when I will come back to work on it

**Comment by ACastanza** [comment]
Small update here, I did still experience the issue after blacklisting explorer.exe, but it seems like the new dev channel Windows 11 build has resolved whatever bad behavior was being triggered on the Microsoft end. I'm going to tentatively close this issue under the assumption that there isn't actually anything you need to do here if Microsoft's fix sticks.
