### ISSUE TITLE
GAMERS BEWARE

### ISSUE THREAD

**Issue by MeSoFruity** [BiGilSoft/WindowTop#150]
Downloading this program onto your PC will cause you to get permanently banned in games, regardless of if you use the software to cheat or not. DO NOT DOWNLOAD

**Comment by Gitoffthelawn** [comment]
That's simply not true.  Lawfully downloading software can't get you banned from anything.  Making enough false statements on GitHub, however, could possibly get you banned from GitHub. ;)

You mentioned "downloading" this software twice.  Now, if you actually meant having the software running is getting you banned from some unspecified game, just disable the software when you play that game.  Or contact the developer of that game to figure out what is going on.  But coming onto GitHub insisting that people not download this excellent tool for an issue caused by some game is inappropriate conduct.

**Comment by Gitoffthelawn** [comment]
@gileli121 You're welcome.  You work hard and it's not appropriate to blame your product for something that's not your responsibility.
