### ISSUE TITLE
[Anchors] Firefox playing on full screen is not generating anchor

### ISSUE THREAD

**Issue by cpasoft** [BiGilSoft/WindowTop#200]
If you have a background firefox in full screen mode (for example, playing a youtube video on full screen mode), then you won't have an anchor for this background window...

Tested on 5.8.0 stable and 5.10.0-beta2

**Comment by gileli121** [comment]
@cpasoft 
I was able to reproduce the issue.
I can see why it happened.
For now the workaround is to go to taskbar settings and select this option:
![image](https://user-images.githubusercontent.com/17680514/154808228-d05719b6-922c-43b2-9402-6c565b0372c9.png)

It will automatically hide the taskbar.
I think that you don't need taskbar anyway because anchors should do better job than the taskbar
