### ISSUE TITLE
[Shrink] Total Commander don't change...

### ISSUE THREAD

**Issue by DBX31** [BiGilSoft/WindowTop#236]
Hi

Find the problem:
![WiseTray_k76mSsd2Zd](https://user-images.githubusercontent.com/102855534/173810869-44e97514-f898-42e3-86dc-42e2cd20ce80.gif)

What do you think ?

Thanks

Best regards
DBX

**Comment by gileli121** [comment]
@DBX31 
I know this issue.
Try to configure the app to run as admin.

Go to settings:
![image](https://user-images.githubusercontent.com/17680514/173846587-344c1576-c63b-413a-90d1-d9e63b78f09c.png)

Select "General" tab
![image](https://user-images.githubusercontent.com/17680514/173846687-fc55b481-a894-4542-b48d-87a74ae4e943.png)

Enable this option:
![image](https://user-images.githubusercontent.com/17680514/173846786-bc51adc8-1f7b-4e4b-b8bf-c5cefe8b01ba.png)


After that restart WindowTop and try again.
Let me know if it fixed.

**Comment by gileli121** [comment]
There is no such option in the Microsoft Store version due to the limitations of the OS for store apps.
But I can implement behavior that in cases like this, the program will ask you to rerun it and you will need to approve it via the prompt.

I count it as another vote for 
https://github.com/BiGilSoft/WindowTop/discussions/224

Please vote for #224  so it will be easier for me to see what more frequently wanted

**Comment by gileli121** [comment]
I am closing this issue.
The request is tracked via #224
