### ISSUE TITLE
Sometimes HotKeys are not working for shrunk windows

### ISSUE THREAD

**Issue by Mystqr4** [BiGilSoft/WindowTop#247]
Using commands to shrink windows and then using another command straight after fails. Does the shrunk window fall out of focus which is why the commands do not work straight after or is there some sort of bug that prevents the commands from taking? It would be nice if I could perform commands one after the other without having to pull up the toolbar menu first and then using the commands.

Also not sure but I have been checking for updates within the application and it has said I have the latest version but to my surprise upon visiting github there was a new release available two days ago. Is the update server not in line with the releases or is there some sort of problems.

**Comment by gileli121** [comment]
@Mystqr4 
Thanks for the report.
I can't reproduce it.
Do you mean to use the shrink hotkey twice and on the second time, it did not unshrink it (because it lost focus)?

Please try v5.15
Maybe it will not happen in 5.15

About the update issue, I forgot to update the update notification on the server.
I did it now.

**Comment by gileli121** [comment]
@Mystqr4 
Never mind.
I just reread your message...
Sometimes when reading a second time after a day I understand what the user says.

I was able to reproduce the problem.
The issue is for example when you first shrink the window using a hotkey, and after that, you enable opacity with a hotkey.
In such a case, I see that the opacity command did not apply to the new shrunk window.

But it does work as expected if you try to unshrink it using the hotkey.

The bug happens when the second command is not Shrink.

**Comment by Mystqr4** [comment]
Excellent! Thank you for your understanding and working on the problem. I was just in between rewriting it after carrying out some further testing and even try to screen capture it but the capture was not coming out correctly using ShareX.

I noticed that additionally with the newest version that sort of half does it but gets confused. When I hit ALT + Q and shrink the window and then hit ALT + A then unshrunk window will then appear underneath the shrunk window in opacity whilst the shrunk version remains also visible on top without any opacity settings.
I have also disabled the new feature to "Show Original Window"

**Comment by gileli121** [comment]
No problem :)
About the new issue, can you send recording?

Use this app and record it as gif file:
https://www.screentogif.com/
It is very easy to setup

**Comment by Mystqr4** [comment]
Cool! I always forget about that software.
I had to play around with the settings to get it to capture what I mean. It might be a bit longer than necessary and repetitive.

https://s8.gifyu.com/images/bugf7c3064189bdcc87.gif

**Comment by gileli121** [comment]
I see.
It is about the same issue.
What happened here when you enabled opacity via hotkey, it actually broke the hide-window magic..
It set up the opacity effect to the original window.

Maybe it is even a different bug. but I will handle this case also in this ticket.

**Comment by Mystqr4** [comment]
Excellent!! You are fantastic!
No regrets about buying this software.

If I find any other bugs I will make a post about it and try follow it up with a screen capture.

**Comment by gileli121** [comment]
I'm glad to hear that!
There is nothing out there on the level of WindowTop.
Nothing, trust me about that.

The only issue here is that I am not Microsoft...
If this app was released under Microsoft's name, it could be super popular.
They have some productivity app called PowerToys and PowerToys is not near to the level of this app when it comes to window management features but what I really hate is that every time they make a release, everyone talks about it... 

But you know what, when I see the user's reviews I feel good. WindowTop got a higher rate and 99% of users are happy.
Some of them come to this app after they tried their app because their app is much more buggy - a fact that these youtubers will not tell you. 

In the end, I know that I will not win but at least it is for the wrong reasons.
If you really liked the app, I will be very thankful to you if you will spread the word and if you can make a video, please do so

**Comment by Mystqr4** [comment]
You are so right.
I started with various applications such as moo0 WindowsMenuPlus/always on top and now I use system smart menu as well as WindowTop but there is nothing like WindowTop at all and I don't expect there ever will be.

Yeah but if there is anything I have learned over the many years on this earth is that Microsoft is incredibly slow and only now started to allow tabbed windows and even then it's such a poor and basic implementation that's light years what has been done by many before them.
I feel like everyone talks about Microsoft because they do silly things such as the above.

I'm surprised there aren't people shouting this application out the rooftops. It's pretty great and unique.
WindowTop seems pretty solid. I have had some minor issues with perhaps the tool bar menu sometimes being erratic on hover whilst watch videos and such but that may be on my end. I have also found that if I spam commands for say opacity it might hang at which point I restart the application and its fine. (doesn't happen very often)

I will always be singing its praises and spread the word. Your tireless development alone is of distinction and noteworthy.
I don't often play around with youtube in that way but will share it around where I can and offer my opinions on it. Given I paid for the full version I can also offer people greater insight on what it can offer and share my experiences.

I feel like everyone should give this software a try and see if its for them. I feel like they will be pleasantly surprised.

**Comment by gileli121** [comment]
Thank you :)
Back to the topic, I will work on a fix this weekend

**Comment by gileli121** [comment]
@Mystqr4 
Please test v5.16 from here
https://github.com/BiGilSoft/WindowTop/issues/249
It contains the fix from this ticket and a new feature that I just developed.
Please share your feedback and let me know how it works

**Comment by Mystqr4** [comment]
I just tested this release and the issue seems to have been fixed now. I did notice that there can be a delay on ALT + A randomly on first try but that could be consequence of system resources on my end, once it begins working after waiting a while or spamming the commands it seems to work without issue. I am not sure what new feature you added if any other but I haven't found it yet. I am very happy with the fix so far. Excellent work!!

**Comment by Mystqr4** [comment]
Preview on mouse hover is no longer working now with version 5.16

New feature seams to be working well from my initial testing

**Comment by gileli121** [comment]
@Mystqr4 
Great that this issue is fixed.
The feature that I added is something that I wanted long ago.
There is mouse interact mode: 
![image](https://user-images.githubusercontent.com/17680514/179193860-bbc04c7c-477f-46ac-ac47-447ff68e023f.png)

If this feature is enabled, any mouse operations (such as click, scroll, hover, etc) that you will do on the small PiP window will redirect to the original window. So you have full control of the original window via the PiP window.
This feature is off by default (because it is not stable with every window.. but it is super stable with chrome, firefox, edge, and a few more apps), and to enable it, you need to click on the "INTERACT" button.
This feature is not the new stuff. 

The new thing is what I added to this feature now.
First I will explain the problem - even if you have full control of the original window via the PiP window, you have a hard time seeing what you are doing with the mouse because everything is too small.
This is why the bigger preview feature invented but this bigger preview (when the mouse hovering on the PiP) doesn't tell you where the mouse is located so you need to look at the smaller preview (PiP window) to see where is the mouse and also on the bigger preview to be able to read the stuff on the window.

The thing that I added is that now the bigger preview will also show the mouse so now you don't need to look on 2 places.


Please check beta2 from https://github.com/BiGilSoft/WindowTop/issues/249 
Maybe the new issue you found is resolved there.

Can I close this ticket and your response to me in #249 ?
Thank you for your efforts in testing it!

**Comment by Mystqr4** [comment]
Interesting! Sounds great. I think I tested that feature and it appeared to be working. Good move. It's always great when you are able to knock something off of your to do list.
I'm sure lots of people will appreciate you adding that feature.

Yep, I will close this ticket now. 
Thank you so much.
