### ISSUE TITLE
Album art isn't filtered out from force dark mode on iTunes

### ISSUE THREAD

**Issue by MercfifulZephyr** [BiGilSoft/WindowTop#279]
Album art on songs in iTunes is color inverted even with the filter images option enabled. Also, when in windowed mode a playlist's image is correctly filtered and not color inverted while the same playlist is image is color inverted when the window is maximized/fullscreen. 

Maximized
![Maximized](https://user-images.githubusercontent.com/120707665/208042552-86a6d6dc-21b9-49ff-9b43-90a4a3dd8c6a.png)

Windowed
![Windowed](https://user-images.githubusercontent.com/120707665/208043398-5b7598f2-bc0f-49cc-8f70-1f76222a7df7.png)

**Comment by gileli121** [comment]
@MercfifulZephyr 
Unforanchly, the dark mode algorithm can't be better, and there is nothing else that I can do.
It has already been optimized & improved a lot in the last version (5.19) and should detect at least 80% of the images.
But it will skip small images due to performance optimization.
If I fix this bug, it may greatly impact the rendering speed.

Maybe making it something configurable may be a good idea.
But it must be in advanced settings.

**Comment by MercfifulZephyr** [comment]
I see, thanks for looking into it. It would be nice if such an option was added, but if not, I totally understand.
