### ISSUE TITLE
where to see my activation key

### ISSUE THREAD

**Issue by DavidHJong** [BiGilSoft/WindowTop#280]
I purchased a key and activated the software. But the software crashed a lot recently. So, I decided to reinstall it. But after reinstallation, it asks me for an activation key. Where should I get it?

**Comment by gileli121** [comment]
Hi, what version did you use before reinstalling? 
If it is an older version, then updating may help to solve the problem.
A few older versions like 5.17.x indeed may be more unstable.

If it was 5.19, I suggest you send me the `settings.json` file (from `%AppData%/WindowTop`) via email (not here since it may contain the activation key).

About the activation key, did you check your email including spam? You should have it there.
If you can't find it, please send your email via https://windowtop.info/contact/ and I will try to find the order.

**Comment by gileli121** [comment]
Closed due to inactivity
