### ISSUE TITLE
Publish WindowTop to Microsoft Store

### ISSUE THREAD

**Issue by gileli121** [BiGilSoft/WindowTop#94]

**Comment by WZ-Tong** [comment]
Wait for it!!!
(Seems like that it's still under progress)

**Comment by Pawloland** [comment]
I am looking forward to it. Hope it will happen soon, mostly because I prefer to able to purchase paid version through a MS store.

**Comment by gileli121** [comment]
Thanks for the feedback.
I planed to publish it to steam but maybe first I will publish to MS Store

**Comment by Pawloland** [comment]
> I planed to publish it to steam but maybe first I will publish to MS Store
I didn't think of that. Steam is also a good idea. I think the more options the better, right 😄

**Comment by gileli121** [comment]
The thing I like in steam is that it is cross platform.. one day in the feature maybe we will have version for Mac and Linux
So in one store you can purchase it for any platform

**Comment by gileli121** [comment]
Marked as planed for next big update

**Comment by gileli121** [comment]
Seems that it will be much easy to deploy it to MS store of Windows 11
Because from my understanding there is no longer need to convert the app to UWP.
So for now I will skip this task

**Comment by gileli121** [comment]
I decided that I will implement it now without waiting

**Comment by gileli121** [comment]
@Pawloland 

It was done
It will take some time until it will be approved by Microsoft.

For now you will have to wait a little.

After that you will able to search for WindowTop in the store and install it, purchase it using Microsoft Store purchase system.

**Comment by gileli121** [comment]
@Pawloland 
The Microsoft Store version is out!

Get it from here:
ms-windows-store://pdp/?ProductId=9PG6GHB4CT57

Or search for "WindowTop" in Microsoft Store.

I will soon add link on the official website

Enjoy!

**Comment by Pawloland** [comment]
I just bought it. So far so good. I have just 3 questions left.
1. I am on the Windows 10 (not 11) and have the old ms store. Is this uploaded to ms store version an uwp app or does the old store somehow also serve win32 apps?

2. Is the auto update functionality done through the ms store or is it done by the app itself (if it isn't uwp)?

3. Could it be possible to use the Windows notifications rather than those custom ones? My understanding is that those custom ones were selected because they hint a user that something is going right or wrong, by setting background to red or green and by being overall more eye pleasing than the native ones. I personally prefer to use the native ones, because I can go back to them at any time to see what was happening. I can also globally disable them with Windows focus assist. Not having these things is a big trade off for me that I don't like to make. 

From here as a happy pro user I would like to humbly ask you to at least make it an option to use the native notifications in near future.

Cheers!

**Comment by gileli121** [comment]
1. The new store in Win11 should show also any UWP apps (or packaged Win32 apps that are packaged as UWP) for Windows 10. I am not aware of a plan from MS to drop support for old apps in the store..  And if they will do it, they will damage their own business because there are a lot of paid games out there, and dropping support for it means losing a lot of money.


Btw, this version is not a pure UWP app. In is Win32/WPF app that packaged as UWP.
But it has full access to almost any UWP/WinRT APIs so you can consider it as a UWP app because it behaves exactly as UWP app behaves. 

2. The update functionality in the UWP version is done via Microsoft Store. This version will check for updates by connecting to the Microsoft Store server (API) and check if there is a new update. If there is a new update, it should suggest you update it directly via Microsoft Store.

3. OK, I see your point. Please open another issue (request) here about the notifications.

Thanks for your feedback.

**Comment by Pawloland** [comment]
Oh, I may worded myself wrongly and you misunderstood my first point. I am sorry. English isn't my first language.

What I meant:
Is the version of the app that was submitted by you to ms store uwp or Win32?

Luckily I got the answer that I was looking for,  but I will explain myself anyway.

Because Windows 11 added support for win32 I was curious if version you uploaded was Win32. If it was Win32 it shouldn't show up for me on win 10 in old Ms store, but it did show and I wondered whether old ms store already gained support for win32 apps as it was promised by Microsoft, that it will happen.

I will make new issue tomorrow.
Thanks for quick answers!

**Comment by gileli121** [comment]
Great!

I preferred to package it as a UWP app because then I have all UWP APIs available (And there are some good stuff out there)
If I will wait for the store to support Win32, not only that it will take time, I will also not have these APIs.

@Pawloland 
Please note that in the current UWP version, there is a bug that I just found.
The check for updates functionality does not work. It will always think that the last version was installed.
I fixed the issue and submitted a new version to the store. The version is v5.4.12 

It is not yet released, but when it will be released to the store I will update you.
You will need to update it manually via the Microsoft Store app.

**Comment by gileli121** [comment]
It was released now with the hotfix for check for updates functionality.
Please update it manually from the store app.
